name: 'Lazarus Project/Package version bumper'
description: 'Bump the version of a Lazarus Project or Package while also adding a git tag based on the commit message'
author: 'Torsten Bonde Christiansen'
input:
  GITHUB_TOKEN:
    description: Personal Access Token for GitHub for pushing the code
    required: true
    default: ""
  PROJECT_FILENAMES:
    description: The filename(s) containing the lazarus project/packages. Separate by spaces if more than one.
    required: true
    default: "project1.lpi"
  DRY_RUN:
    description: Perform all collecting actions but do not update project/package file or tag the repo.
    required: false
    default: false
runs:
  using: 'docker'
  image: 'docker://epidata/modify-lazarus-action:0.1'
branding:
  icon: 'git-merge'  
  color: 'purple'
